IntelliDataSmart/Accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views
from django.urls import reverse

app_name = 'Accounts'

urlpatterns = [
    url(r"login/$", auth_views.LoginView.as_view(template_name="Accounts/login.html"),name='login'),
    url(r"logout/$", auth_views.LogoutView.as_view(), name="logout"),
    url(r"signup/$", views.SignUp.as_view(), name="signup"),
    url(r"editprofile/(?P<pk>\d+)/$", views.EditProfile.as_view(), name="editprofile"),
]

IntelliDataSmart/IntelliDataSmart/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from controlcenter.views import controlcenter
from django.urls import reverse

urlpatterns = [
    url(r"^$", views.HomePage.as_view(), name="home"),
    url(r"^landing/$", views.TestPage.as_view(), name="test"),
    url(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"),
    url(r"^gotoadmin/$", views.GotoAdmin, name="admin"),
    url(r"^admin/", admin.site.urls),
    url(r"^admin/dashboard/", controlcenter.urls),
    url(r"^accounts/", include("Accounts.urls", namespace="accounts")),
    url(r"^accounts/", include("django.contrib.auth.urls")),
    url(r"^members/", include("members.urls", namespace="members")),
    url(r"^groups/",include("groups.urls", namespace="groups")),
    url(r"^products/",include("products.urls", namespace="products")),
    url(r"^agreements/",include("agreements.urls", namespace="agreements")),
]

IntelliDataSmart/groups/urls.py
from django.conf.urls import url

from . import views

app_name = 'groups'

urlpatterns = [
    url(r"^$", views.ListGroups.as_view(), name="all"),
    url(r"^new/$", views.CreateGroup.as_view(), name="create"),
    url(r"^search/$", views.SearchGroupsForm, name="search"),
    url(r"^(?P<pk>\d+)/members/show/$", views.ShowMembersList.as_view(), name="show_members"),
    url(r"^(?P<pk>\d+)/agreements/show/$", views.ShowAgreementsList.as_view(), name="show_agreements"),
    url(r"^search/results/$", views.SearchGroupsList.as_view(), name="search_results"),
    url(r"^posts/in/(?P<pk>\d+)/$",views.SingleGroup.as_view(),name="single"),
    url(r"^version/(?P<pk>\d+)/$",views.VersionGroup, name="version"),
    url(r"^update/(?P<pk>\d+)/$",views.UpdateGroup.as_view(),name="update"),
    url(r"^delete/(?P<pk>\d+)/$",views.DeleteGroup.as_view(),name="delete"),
    url(r"^bulkupload/$",views.BulkUploadGroup,name="bulk"),
    url(r"join/(?P<slug>[-\w]+)/$",views.JoinGroup.as_view(),name="join"),
    url(r"leave/(?P<slug>[-\w]+)/$",views.LeaveGroup.as_view(),name="leave"),
    url(r"^rest/$",views.GroupList, name="rest"),
]

IntelliDataSmart/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Intelli Data</title>
    <!-- Latest compiled and minified CSS -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'simplesocial/css/master.css'%}">


  </head>


  <body data-spy="scroll" data-target=".navbar">
    <div class="navigation">
      <nav class="navbar navbar-default navbar-inverse navbar-fixed-top" role="navigation" id="navbar">
    			<div class="container">

            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">

              <!--  Code for the hamburger icon-->
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>

            <a class="navbar-brand mynav" href="{% url 'home' %}">Home</a>
            &nbsp;
            <a class="navbar-brand mynav" href="{% url 'admin' %}">Admin</a>
            &nbsp;
            <a class="navbar-brand mynav" href="http://127.0.0.1:8000/admin/dashboard/mydash/">Dashboard</a>

            <!-- Anything inside of collapse navbar-collapse goes into the "hamburger" -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    					<ul class="nav navbar-nav navbar-right">
    						{% if user.is_authenticated %}

                      <div class="dropdown">
                        <li><a class="navbar-brand mynav" href="#" class="btn btn-simple">Search</a></li>
                        <div class="dropdown-content">

                          <li><a class="navbar-brand mynav" href="{% url 'groups:search' %}" class="btn btn-simple">Group</a></li>
                          <li><a class="navbar-brand mynav" href="{% url 'members:search' %}" class="btn btn-simple">Member</a></li>
                          <li><a class="navbar-brand mynav" href="{% url 'products:search' %}" class="btn btn-simple">Product</a></li>
                          <li><a class="navbar-brand mynav" href="{% url 'agreements:search' %}" class="btn btn-simple">Agreement</a></li>

                        </div>
                      </div>

                      <li><a class="navbar-brand mynav" href="{% url 'groups:all' %}" class="btn btn-simple">Groups</a></li>
                      <li><a class="navbar-brand mynav" href="{% url 'members:all' %}" class="btn btn-simple">Members</a></li>
                      <li><a class="navbar-brand mynav" href="{% url 'products:all' %}" class="btn btn-simple">Products</a></li>
                      <li><a class="navbar-brand mynav" href="{% url 'agreements:all' %}" class="btn btn-simple">Agreements</a></li>


                      <li><a class="navbar-brand mynav" href="{% url 'Accounts:logout' %}">Log out</a></li>
                      <li><a class="navbar-brand mynav" href="{% url 'Accounts:editprofile' pk=user.pk %}">MyProfile</a></li>
    						{% else %}
    						  <!--    <li><a href="{% url 'accounts:login' %}" class="btn btn-simple">Log in</a></li>
    						      <li><a href="{% url 'accounts:signup' %}" class="btn btn-simple">Sign up</a></li> -->
                      <li><a class="navbar-brand mynav" href="{% url 'Accounts:login' %}">Log in</a></li>
    						      <li><a class="navbar-brand mynav" href="{% url 'Accounts:signup' %}">Sign up</a></li>
    						{% endif %}
    					</ul>



    			</div>
        </div>
    	</nav>
    </div>

    <br>
    <br>
    <br>
    <br>

        <div class="container mycontent">
          {% block content %}

          {% endblock %}

        </div>

      <style>
          body {
            background-image: url('{% static "images/darknewyorkcity.jpg" %}');
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: cover;
            overflow: scroll;
          }
      </style>

<canvas id="canvas"></canvas>

<script
src="http://code.jquery.com/jquery-3.1.1.js"
integrity="sha256-16cdPddA6VdVInumRGo6IbivbERE8p7CQR3HzTBuELA="
crossorigin="anonymous"></script>  <!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


  </body>
<!--  <script src="{% static "simplesocial/js/master.js"%}" type="text/javascript" ></script>  -->

 <script src="{% static "simplesocial/js/product_table.js"%}" type="text/javascript" ></script>


</html>

IntelliDataSmart/templates/base0.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Intelli Data</title>
    <!-- Latest compiled and minified CSS -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'simplesocial/css/master.css'%}">


  </head>


  <body data-spy="scroll" data-target=".navbar">
    <div class="navigation">
      <nav class="navbar  mynav" role="navigation" id="navbar">
    			<div class="container">

            <a class="navbar-brand mynav" href="{% url 'home' %}">Home</a>

    					<ul class="nav navbar-nav navbar-right">
    						{% if user.is_authenticated %}
                      <li><a class="navbar-brand mynav" href="{% url 'groups:all' %}" class="btn btn-simple">Groups</a></li>
                      <li><a class="navbar-brand mynav" href="{% url 'members:all' %}" class="btn btn-simple">Members</a></li>
                      <li><a class="navbar-brand mynav" href="{% url 'products:all' %}" class="btn btn-simple">Products</a></li>
                      <li><a class="navbar-brand mynav" href="{% url 'groups:search' %}" class="btn btn-simple">Search Group</a></li>
                      <li><a class="navbar-brand mynav" href="{% url 'members:search' %}" class="btn btn-simple">Search Member</a></li>
                      <li><a class="navbar-brand mynav" href="{% url 'products:search' %}" class="btn btn-simple">Search Product</a></li>
                      <li><a class="navbar-brand mynav" href="{% url 'Accounts:logout' %}">Log out</a></li>
    						{% else %}
    						  <!--    <li><a href="{% url 'accounts:login' %}" class="btn btn-simple">Log in</a></li>
    						      <li><a href="{% url 'accounts:signup' %}" class="btn btn-simple">Sign up</a></li> -->
                      <li><a class="navbar-brand mynav" href="{% url 'Accounts:login' %}">Log in</a></li>
    						      <li><a class="navbar-brand mynav" href="{% url 'Accounts:signup' %}">Sign up</a></li>
    						{% endif %}
    					</ul>



    			</div>
    	</nav>
    </div>

        <div class="container mycontent">
          {% block content %}

          {% endblock %}

        </div>

      <style>
          body {
            background-image: url('{% static "images/darknewyorkcity.jpg" %}');
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: cover;
            overflow: scroll;
          }
      </style>

<canvas id="canvas"></canvas>

  </body>
<!--  <script src="{% static "simplesocial/js/master.js"%}" type="text/javascript" ></script>  -->

</html>

IntelliDataSmart/templates/base1.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Intelli Data1</title>
    <!-- Latest compiled and minified CSS -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'simplesocial/css/master.css'%}">


  </head>


  <body data-spy="scroll" data-target=".navbar">
    <div class="navigation">
      <nav class="navbar navbar-default navbar-inverse navbar-fixed-top" role="navigation" id="navbar">
    			<div class="container">

            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">

              <!--  Code for the hamburger icon-->
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>

            <a class="navbar-brand mynav" href="{% url 'home' %}">Home</a>
            <!-- Anything inside of collapse navbar-collapse goes into the "hamburger" -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    					<ul class="nav navbar-nav navbar-right">
    						{% if user.is_authenticated %}
                      <li><a class="navbar-brand mynav" href="{% url 'groups:all' %}" class="btn btn-simple">Groups</a></li>
                      <li><a class="navbar-brand mynav" href="{% url 'members:all' %}" class="btn btn-simple">Members</a></li>
                      <li><a class="navbar-brand mynav" href="{% url 'products:all' %}" class="btn btn-simple">Products</a></li>
                      <li><a class="navbar-brand mynav" href="{% url 'groups:search' %}" class="btn btn-simple">Search Group</a></li>
                      <li><a class="navbar-brand mynav" href="{% url 'members:search' %}" class="btn btn-simple">Search Member</a></li>
                      <li><a class="navbar-brand mynav" href="{% url 'products:search' %}" class="btn btn-simple">Search Product</a></li>
                      <li><a class="navbar-brand mynav" href="{% url 'Accounts:logout' %}">Log out</a></li>
    						{% else %}
    						  <!--    <li><a href="{% url 'accounts:login' %}" class="btn btn-simple">Log in</a></li>
    						      <li><a href="{% url 'accounts:signup' %}" class="btn btn-simple">Sign up</a></li> -->
                      <li><a class="navbar-brand mynav" href="{% url 'Accounts:login' %}">Log in</a></li>
    						      <li><a class="navbar-brand mynav" href="{% url 'Accounts:signup' %}">Sign up</a></li>
    						{% endif %}
    					</ul>



    			</div>
        </div>
    	</nav>
    </div>

    <br>
    <br>
    <br>
    <br>

        <div class="container mycontent">
          {% block content %}

          {% endblock %}

        </div>

      <style>
          body {
            background-image: url('{% static "images/darknewyorkcity.jpg" %}');
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: cover;
            overflow: scroll;
          }
      </style>

<canvas id="canvas"></canvas>

<script
src="http://code.jquery.com/jquery-3.1.1.js"
integrity="sha256-16cdPddA6VdVInumRGo6IbivbERE8p7CQR3HzTBuELA="
crossorigin="anonymous"></script>  <!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  </body>
<!--  <script src="{% static "simplesocial/js/master.js"%}" type="text/javascript" ></script>  -->

</html>

IntelliDataSmart/templates/index.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Intelli Data</title>
    <!-- Latest compiled and minified CSS -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'simplesocial/css/master.css'%}">


  </head>


  <body data-spy="scroll" data-target=".navbar">
    <div class="navigation">
      <nav class="navbar navbar-default navbar-inverse navbar-fixed-top" role="navigation" id="navbar">
    			<div class="container">

            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">

              <!--  Code for the hamburger icon-->
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>

            <a class="navbar-brand mynav" href="{% url 'home' %}">Home</a>
            <!-- Anything inside of collapse navbar-collapse goes into the "hamburger" -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    					<ul class="nav navbar-nav navbar-right">
    						{% if user.is_authenticated %}
                      <li><a class="navbar-brand mynav" href="{% url 'groups:all' %}" class="btn btn-simple">Groups</a></li>
                      <li><a class="navbar-brand mynav" href="{% url 'members:all' %}" class="btn btn-simple">Members</a></li>
                      <li><a class="navbar-brand mynav" href="{% url 'products:all' %}" class="btn btn-simple">Products</a></li>
                      <li><a class="navbar-brand mynav" href="{% url 'agreements:all' %}" class="btn btn-simple">Agreements</a></li>

                      <div class="dropdown">
                        <li><a class="navbar-brand mynav" href="#" class="btn btn-simple">Search</a></li>
                        <div class="dropdown-content">

                          <li><a class="navbar-brand mynav" href="{% url 'groups:search' %}" class="btn btn-simple">Group</a></li>
                          <li><a class="navbar-brand mynav" href="{% url 'members:search' %}" class="btn btn-simple">Member</a></li>
                          <li><a class="navbar-brand mynav" href="{% url 'products:search' %}" class="btn btn-simple">Product</a></li>
                          <li><a class="navbar-brand mynav" href="{% url 'agreements:search' %}" class="btn btn-simple">Agreement</a></li>

                        </div>
                      </div>

                      <li><a class="navbar-brand mynav" href="{% url 'Accounts:logout' %}">Log out</a></li>
                      <li><a class="navbar-brand mynav" href="{% url 'Accounts:editprofile' %}">Edit Profile</a></li>
    						{% else %}
    						  <!--    <li><a href="{% url 'accounts:login' %}" class="btn btn-simple">Log in</a></li>
    						      <li><a href="{% url 'accounts:signup' %}" class="btn btn-simple">Sign up</a></li> -->
                      <li><a class="navbar-brand mynav" href="{% url 'Accounts:login' %}">Log in</a></li>
    						      <li><a class="navbar-brand mynav" href="{% url 'Accounts:signup' %}">Sign up</a></li>
    						{% endif %}
    					</ul>



    			</div>
        </div>
    	</nav>
    </div>

    <br>
    <br>
    <br>
    <br>

        <div class="container mycontent">

          <h1>Welcome to IntelliDataSmart!</h1>
          <h2>A smart data platform for modern businesses!</h2>
          <h2>Login or Sign-up to get started!</h2>

      <!--    <img src="{% static "images/background.png" %}" alt="Image not available!">  -->

        </div>


<!-- corona tag -->
<canvas id="canvas"></canvas>
<canvas id="orbits"></canvas>


  </body>
<!--  <script src="{% static "simplesocial/js/master.js"%}" type="text/javascript" ></script> -->
<div class="container corona">
 <script src="{% static "simplesocial/js/corona.js"%}" type="text/javascript" ></script>
</div>

</html>

IntelliDataSmart/templates/test.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <h1>You are now logged in! {{user.username }}</h1>
  <h2><a href="{% url 'groups:all'%}">Go to Groups</a></h2>



</div>

{% endblock %}

IntelliDataSmart/templates/thanks.html
{% extends "base.html" %}
{% block content %}
<h1>Thanks for visiting! Come back soon!</h1>

{% endblock %}