IntelliDataSmart/IntelliDataSmart/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from controlcenter.views import controlcenter
from django.urls import reverse

urlpatterns = [
    url(r"^$", views.HomePage.as_view(), name="home"),
    url(r"^landing/$", views.TestPage.as_view(), name="test"),
    url(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"),
    url(r"^gotoadmin/$", views.GotoAdmin, name="admin"),
    url(r"^admin/", admin.site.urls),
    url(r"^admin/dashboard/", controlcenter.urls),
    url(r"^accounts/", include("Accounts.urls", namespace="accounts")),
    url(r"^accounts/", include("django.contrib.auth.urls")),
    url(r"^members/", include("members.urls", namespace="members")),
    url(r"^groups/",include("groups.urls", namespace="groups")),
    url(r"^products/",include("products.urls", namespace="products")),
    url(r"^agreements/",include("agreements.urls", namespace="agreements")),
]

IntelliDataSmart/groups/urls.py
from django.conf.urls import url

from . import views

app_name = 'groups'

urlpatterns = [
    url(r"^$", views.ListGroups.as_view(), name="all"),
    url(r"^new/$", views.CreateGroup.as_view(), name="create"),
    url(r"^search/$", views.SearchGroupsForm, name="search"),
    url(r"^(?P<pk>\d+)/members/show/$", views.ShowMembersList.as_view(), name="show_members"),
    url(r"^(?P<pk>\d+)/agreements/show/$", views.ShowAgreementsList.as_view(), name="show_agreements"),
    url(r"^search/results/$", views.SearchGroupsList.as_view(), name="search_results"),
    url(r"^posts/in/(?P<pk>\d+)/$",views.SingleGroup.as_view(),name="single"),
    url(r"^version/(?P<pk>\d+)/$",views.VersionGroup, name="version"),
    url(r"^update/(?P<pk>\d+)/$",views.UpdateGroup.as_view(),name="update"),
    url(r"^delete/(?P<pk>\d+)/$",views.DeleteGroup.as_view(),name="delete"),
    url(r"^bulkupload/$",views.BulkUploadGroup,name="bulk"),
    url(r"join/(?P<slug>[-\w]+)/$",views.JoinGroup.as_view(),name="join"),
    url(r"leave/(?P<slug>[-\w]+)/$",views.LeaveGroup.as_view(),name="leave"),
    url(r"^rest/$",views.GroupList, name="rest"),
]

IntelliDataSmart/members/urls.py
from django.conf.urls import url

from . import views

app_name = 'members'

urlpatterns = [
    url(r"^$",views.ListMembers.as_view(),name='all'),
    url(r"^(?P<pk>\d+)/$",views.SingleMember.as_view(),name='single'),
    url(r"^version/(?P<pk>\d+)/$",views.VersionMember, name="version"),
    url(r"^search/$", views.SearchMembersForm, name="search"),
    url(r"^search/results/$", views.SearchMembersList.as_view(), name="search_results"),
    url(r"^(?P<pk>\d+)/create/$",views.CreateMember.as_view(),name='create'),
    url(r"^(?P<pk>\d+)/upload/$",views.BulkUploadMember, name='upload'),
    url(r"^update/(?P<pk>\d+)/$",views.UpdateMember.as_view(),name='update'),
    url(r"^delete/(?P<pk>\d+)/$",views.DeleteMember.as_view(),name='delete'),
    url(r"^rest/$",views.MemberList, name="rest"),
]

IntelliDataSmart/groups/models.py
from datetime import datetime
from django.conf import settings
import uuid
from django.contrib.auth.models import User
#from django.core.urlresolvers import reverse
from django.db import models
from django.utils.text import slugify
from groups.utils import create_new_ref_number

# from accounts.models import User

import misaka

from django.contrib.auth import get_user_model
User = get_user_model()

# https://docs.djangoproject.com/en/1.11/howto/custom-template-tags/#inclusion-tags
# This is for the in_group_members check template tag
from django import template
register = template.Library()



class Group(models.Model):
    groupid = models.CharField(max_length=255, null=True, blank=True)
    name = models.CharField(max_length=255)
    slug = models.SlugField(allow_unicode=True)
    description = models.TextField(blank=True, default='')
    description_html = models.TextField(editable=False, default='', blank=True)
    purpose = models.CharField(max_length=255, null=True, default='', blank=True)
    creator = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    group_date = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):

        if (self.groupid == None):
            var = str(uuid.uuid4())
            self.groupid = var[26:36]

        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("groups:single", kwargs={"pk": self.pk})

    class Meta:
        ordering = ["-group_date"]
        unique_together = ("slug", "purpose", "group_date")


class GroupMember(models.Model):
    group = models.ForeignKey(Group, null=True, on_delete=models.SET_NULL, related_name="memberships")
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL,related_name='identity')

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ("group", "user")

IntelliDataSmart/groups/forms.py
from django import forms

from .models import Group


class GroupForm(forms.ModelForm):

    class Meta:
        model = Group
        fields = ('groupid', 'name','description', 'purpose',)

        widgets = {
            'groupid': forms.TextInput(attrs={'readonly':'readonly'}),
            'name': forms.TextInput(attrs={'class': 'textinputclass'}),
            'description': forms.Textarea(attrs={'class': 'editable medium-editor-textarea postcontent'}),
            'purpose': forms.TextInput(attrs={'class': 'textinputclass'}),
        }

IntelliDataSmart/groups/views.py
from django.contrib import messages
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.http import HttpResponseForbidden
from django.core.exceptions import PermissionDenied
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test
import time
from django.shortcuts import render
from django.contrib.auth.models import User
from django.db.models import Q
from django.contrib.auth.mixins import(
    LoginRequiredMixin,
    PermissionRequiredMixin
)

from django.urls import reverse
from django.urls import reverse_lazy
from django.db import IntegrityError
from django.shortcuts import get_object_or_404
from django.views import generic
from django.db.models import Count
from groups.models import Group,GroupMember
from . import models
from . import forms
from members.models import Member
from groups.forms import GroupForm
import csv
from groups.utils import BulkCreateManager
import os.path
from os import path
from django.utils.text import slugify
import misaka
import uuid

# For Rest rest_framework
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response
from groups.serializers import GroupSerializer

#class CreateGroup(LoginRequiredMixin, generic.CreateView):
#    fields = ("name", "description")
#    model = Group

#class SingleGroup(generic.DetailView):
#    model = Group

#class ListGroups(generic.ListView):
#    model = Group


class SingleGroup(LoginRequiredMixin, generic.DetailView):
    context_object_name = 'group_details'
    model = models.Group
    template_name = 'groups/group_detail.html'
    #form_class = forms.GroupForm

class ListGroups(LoginRequiredMixin, generic.ListView):
    model = models.Group
    template_name = 'groups/group_list.html'
    #form_class = forms.GroupForm

    def get_queryset(self):
        return Group.objects.all()
        #self.extra_context["member_count"] = Group.objects.annotate(association_count=Count('member_set'))

class CreateGroup(LoginRequiredMixin, PermissionRequiredMixin, generic.CreateView):
#    fields = ("name", "description")
    permission_required = 'groups.add_group'
    context_object_name = 'group_details'
    redirect_field_name = 'groups/group_list.html'
    form_class = forms.GroupForm
    model = models.Group
    template_name = 'groups/group_form.html'

    def form_valid(self, form):

        if not self.request.user.has_perm('groups.add_group'):
            raise HttpResponseForbidden()
        else:
            form.instance.creator = self.request.user

            return super().form_valid(form)


@permission_required("groups.add_group")
@login_required
def VersionGroup(request, pk):
    # dictionary for initial data with
    # field names as keys


        context ={}

        # fetch the object related to passed id
        obj = get_object_or_404(Group, pk = pk)

        # pass the object as instance in form
        form = GroupForm(request.POST or None, instance = obj)

        # save the data from the form and
        # redirect to detail_view
        if form.is_valid():
                obj.pk = int(round(time.time() * 1000))
                form.instance.creator = request.user
                form.save()
                return HttpResponseRedirect(reverse("groups:all"))

        else:

                # add form dictionary to context
                context["form"] = form

                return render(request, "groups/group_form.html", context)


class UpdateGroup(LoginRequiredMixin, PermissionRequiredMixin, generic.UpdateView):
#    fields = ("name", "description")
    permission_required = 'groups.change_group'
    context_object_name = 'group_details'
    redirect_field_name = 'groups/group_detail.html'
    form_class = forms.GroupForm
    model = models.Group
    template_name = 'groups/group_form.html'

    def form_valid(self, form):

        if not self.request.user.has_perm('groups.change_group'):
            raise HttpResponseForbidden()
        else:
            form.instance.creator = self.request.user
            return super().form_valid(form)


class DeleteGroup(LoginRequiredMixin, PermissionRequiredMixin, generic.DeleteView):
#    fields = ("name", "description")
    permission_required = 'groups.delete_group'
    context_object_name = 'group_details'
    form_class = forms.GroupForm
    model = models.Group
    template_name = 'groups/group_delete_confirm.html'
    success_url = reverse_lazy("groups:all")

    def form_valid(self, form):

        if not self.request.user.has_perm('groups.delete_group'):
            raise HttpResponseForbidden()
        else:
            return super().form_valid(form)


@login_required
def SearchGroupsForm(request):
    return render(request,'groups/group_search_form.html')


class SearchGroupsList(LoginRequiredMixin, generic.ListView):
    model = Group
    template_name = 'groups/group_search_list.html'

    def get_queryset(self, **kwargs): # new
        query = self.request.GET.get('q', None)
        object_list = Group.objects.filter(
            Q(groupid__icontains=query) | Q(name__icontains=query) | Q(description__icontains=query) | Q(purpose__icontains=query)
        )
        return object_list


class ShowMembersList(LoginRequiredMixin, generic.ListView):
    model = Group
    template_name = 'members/member_list.html'

    def get_queryset(self): # new
        group = get_object_or_404(models.Group, pk=self.kwargs['pk'])
        object_list = group.member_set.all()

        return object_list

class ShowAgreementsList(LoginRequiredMixin, generic.ListView):
    model = Group
    template_name = 'agreements/agreement_list.html'

    def get_queryset(self): # new
        group = get_object_or_404(models.Group, pk=self.kwargs['pk'])
        object_list = group.group_set.all()

        return object_list


@permission_required("groups.add_group")
@login_required
def BulkUploadGroup(request):

    if not path.exists('/Users/suvojitdutta/Documents/PYTHON/PROJECTS/Docs/groups.csv'):
        return render(request, "groups/group_list.html", {'FileNotFound': True})
    else:
        with open('/Users/suvojitdutta/Documents/PYTHON/PROJECTS/Docs/groups.csv', 'rt') as csv_file:
            bulk_mgr = BulkCreateManager(chunk_size=20)
            for row in csv.reader(csv_file):
                bulk_mgr.add(models.Group(groupid = str(uuid.uuid4())[26:36],
                                          name=row[0],
                                          slug=slugify(row[0]),
                                          description=row[1],
                                          description_html = misaka.html(row[1]),
                                          purpose=row[2],
                                          creator = request.user
                                          ))
            bulk_mgr.done()

    return HttpResponseRedirect(reverse("groups:all"))


@api_view(['GET', 'POST'])
def GroupList(request):

    if request.method == 'GET':
        contacts = Group.objects.all()
        serializer = GroupSerializer(contacts, many=True)
        return Response(serializer.data)
    elif request.method == 'POST':
        serializer = GroupSerializer(data=request.data)

    if serializer.is_valid():
        serializer.save()

        return Response(serializer.data, status=status.HTTP_201_CREATED)

        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class JoinGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse("groups:single",kwargs={"slug": self.kwargs.get("slug")})

    def get(self, request, *args, **kwargs):
        group = get_object_or_404(Group,slug=self.kwargs.get("slug"))

        try:
            GroupMember.objects.create(user=self.request.user,group=group)

        except IntegrityError:
            messages.warning(self.request,("Warning, already a member of {}".format(group.name)))

        else:
            messages.success(self.request,"You are now a member of the {} group.".format(group.name))

        return super().get(request, *args, **kwargs)


class LeaveGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse("groups:single",kwargs={"slug": self.kwargs.get("slug")})

    def get(self, request, *args, **kwargs):

        try:

            membership = models.GroupMember.objects.filter(
                user=self.request.user,
                group__slug=self.kwargs.get("slug")
            ).get()

        except models.GroupMember.DoesNotExist:
            messages.warning(
                self.request,
                "You can't leave this group because you aren't in it."
            )
        else:
            membership.delete()
            messages.success(
                self.request,
                "You have successfully left this group."
            )
        return super().get(request, *args, **kwargs)

IntelliDataSmart/groups/templates/groups/group_base.html
{% extends "base.html" %}
{% block content %}

<div class="container">
  <div class="row">
    {% block pregroup %}{% endblock %}
    {% block group_content %}{% endblock %}
    {% block postgroup %}{% endblock %}
  </div>
</div>

{% endblock %}

IntelliDataSmart/groups/templates/groups/group_delete_confirm.html
{% extends "groups/group_base.html" %}
{% load bootstrap3 %}

{% block group_content %}
  <form action="" method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input class='btn btn-danger' type="submit" value="Confirm" />
  </form>
{% endblock %}

IntelliDataSmart/groups/templates/groups/group_detail.html
{% extends "groups/group_base.html" %}

{% block pregroup %}

<div class="dropdown">
  <button class="dropbtn btn btn-primary btn-large">Manage Groups</button>
  <div class="dropdown-content">

    <a href="{% url 'members:create' pk=group_details.pk %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-plus-sign"></span> Add Members</a>
    &nbsp;
    <a href="{% url 'members:upload' pk=group_details.pk %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-plus-sign"></span> Upload Members</a>
    &nbsp;
    <a href="{% url 'groups:show_members' pk=group_details.pk %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-ok-circle"></span> Show Members</a>
    &nbsp;
    <a href="{% url 'agreements:create' pk=group_details.pk %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-plus-sign"></span> Create Agreement</a>
    &nbsp;
    <a href="{% url 'groups:show_agreements' pk=group_details.pk %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-ok-circle"></span> Show Ageements</a>
    &nbsp;
    <a href="{% url 'groups:version' pk=group_details.pk %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-pencil"></span> Version Group</a>
    &nbsp;
    <a href="{% url 'groups:update' pk=group_details.pk %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-pencil"></span> Update Group</a>
    &nbsp;
    <a href="{% url 'groups:delete' pk=group_details.pk %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-remove-circle"></span> Delete Group</a>

  </div>
</div>

&nbsp;
<input type="button" class="btn btn-primary btn-large" value="Go back!" onclick="history.back()">
&nbsp;

<h1>{{group_details.name}}</h1>
<h2>Group ID: {{group_details.groupid}}</h2>
<h2>Purpose: {{group_details.purpose}}</h2>
<h2>Created On: {{group_details.group_date}}</h2>
<h2>Created By: {{group_details.creator}}</h2>
<h2>Member Count: {{group_details.member_set.count}}</h2>
<div style="background-color: rgba(255, 255, 255, 0.8);" data-spy="scroll" data-target=".navbar">
  <div class="list-group-item-text container-fluid">
    <h4 style="color:black;">{{ group_details.description_html|safe }}</h4>
  </div>
</div>

{% endblock %}

<!--
<div class="content">


				{% if user in group.members.all %}
					<a href="{% url 'groups:leave' slug=group_details.slug %}" class="btn btn-lg btn-fill btn-warning"><span class="glyphicon glyphicon-remove-circle"></span> Leave</a>
				{% else %}
					<a href="{% url 'groups:join' slug=group_details.slug %}" class="btn btn-lg btn-fill btn-warning"><span class="glyphicon glyphicon-ok-circle"></span> Join</a>
				{% endif %}



</div>

-->



<!--{% block group_content %}

<div class="col-md-8">
	{% if group.posts.count == 0 %}
	<h2>No posts in this group yet!</h2>

	{% else %}

		{% for post in group.posts.all %}
			{% include "posts/_post.html" %}
		{% endfor %}

	{% endif %}
</div>
{% endblock %}-->

IntelliDataSmart/groups/templates/groups/group_detail0.html
{% extends "groups/group_base.html" %}

{% block pregroup %}

<div class="content">

    <a href="{% url 'members:create' pk=group_details.pk %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-plus-sign"></span> Add Members</a>
    &nbsp;
    <a href="{% url 'groups:update' pk=group_details.pk %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-pencil"></span> Update Group</a>
    &nbsp;
    <a href="{% url 'groups:delete' pk=group_details.pk %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-remove-circle"></span> Delete Group</a>
    &nbsp;
    <a href="{% url 'groups:show_members' pk=group_details.pk %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-ok-circle"></span> Show Members</a>
    &nbsp;
    <input type="button" class="btn btn-primary btn-large" value="Go back!" onclick="history.back()">

</div>

<h1>{{group_details.name}}</h1>
<h2>ID: {{group_details.pk}}</h2>
<h2>Purpose: {{group_details.purpose}}</h2>
<h2>Member Count: {{group_details.member_set.count}}</h2>
<div style="background-color: rgba(255, 255, 255, 0.8);" data-spy="scroll" data-target=".navbar">
  <div class="list-group-item-text container-fluid">
    <h4 style="color:black;">{{ group_details.description_html|safe }}</h4>
  </div>
</div>

{% endblock %}

<!--
<div class="content">


				{% if user in group.members.all %}
					<a href="{% url 'groups:leave' slug=group_details.slug %}" class="btn btn-lg btn-fill btn-warning"><span class="glyphicon glyphicon-remove-circle"></span> Leave</a>
				{% else %}
					<a href="{% url 'groups:join' slug=group_details.slug %}" class="btn btn-lg btn-fill btn-warning"><span class="glyphicon glyphicon-ok-circle"></span> Join</a>
				{% endif %}



</div>

-->



<!--{% block group_content %}

<div class="col-md-8">
	{% if group.posts.count == 0 %}
	<h2>No posts in this group yet!</h2>

	{% else %}

		{% for post in group.posts.all %}
			{% include "posts/_post.html" %}
		{% endfor %}

	{% endif %}
</div>
{% endblock %}-->

IntelliDataSmart/groups/templates/groups/group_form.html
{% extends "groups/group_base.html" %}
{% load bootstrap3 %}

{% block group_content %}
<h4>Edit Group</h4>
  <!-- <form method="POST" action="{% url 'groups:create' %}" id="groupForm"> -->
  <form method="POST">
  	{% csrf_token %}
  	{% bootstrap_form form %}
  	<input type="submit" value="Save" class="btn btn-primary btn-large">
    &nbsp;
    <a href="{% url 'groups:all'%}" class="btn btn-primary btn-large">Cancel</a>
  </form>
{% endblock %}

IntelliDataSmart/groups/templates/groups/group_list.html
{% extends "groups/group_base.html" %}

{% block pregroup %}
<div class="col-md-4">
	<div class="content">
		{% if user.is_authenticated %}
		<h2>
			Welcome
			{{user.username }}

		</h2>

    {% endif %}
		<h2>Groups</h2>

		{% if not object_list %}
  			<p>No groups available at this time! Go ahead and create a group if needed!</p>
		{% else %}
				<p>Welcome to the Groups Page! Select a group that you want to work with!</p>
		{% endif %}

	</div>


	<a href="{% url 'groups:create' %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-plus-sign"></span> Create New Group!</a>
	&nbsp;
	<a href="{% url 'groups:bulk' %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-plus-sign"></span> Uplaod Groups!</a>
	&nbsp;
	{% if FileNotFound %}
    <div id="some_flag" title="Some Flag">
        <h2>File Does Not Exist!</h2>
    </div>
	{% endif %}

</div>

<br>

{% endblock %}



{% block group_content %}
<div class="col-md-8">
	<div class="list-group">
		{% for group in object_list %}
			<a class="list-group-item" href="{% url 'groups:single' pk=group.pk %}">
			     <h3 class="title list-group-item-heading">{{ group.name }}</h3>
					 <h4 class="title list-group-item-heading">Group ID: {{ group.groupid }}</h4>
					 <h4 class="title list-group-item-heading">Purpose: {{ group.purpose }}</h4>
					 <h4 class="title list-group-item-heading">Created On: {{ group.group_date }}</h4>
					 <h4 class="title list-group-item-heading">Created By: {{ group.creator }}</h4>
			<div class="list-group-item-text container-fluid">

				<div class="row">
					<div class="col-md-4">
						<span class="badge">{{ group.member_set.count }}</span> member{{ group.member_set.count|pluralize }}
					</div>
				</div>
				<br>
					{{ group.description_html|safe }}
			</div>
		</a>
		{% endfor %}
	</div>
</div>
{% endblock %}

IntelliDataSmart/groups/templates/groups/group_search_form.html
{% extends "groups/group_base.html" %}

{% block pregroup %}
<h4>Search Group</h4>
  <!-- <form method="POST" action="{% url 'groups:create' %}" id="groupForm"> -->
  <form action="{% url 'groups:search_results' %}" method="GET">
  	{% csrf_token %}
    <input name="q" type="text" placeholder="Search...">
    &nbsp;
    <button class="btn btn-primary btn-large" type="submit" >Search</button>
  </form>

{% endblock %}

IntelliDataSmart/groups/templates/groups/group_search_list.html
{% extends "groups/group_base.html" %}
{% load bootstrap3 %}

{% block group_content %}
<div class="col-md-8">
	<div class="list-group">
		{% for group in object_list %}
			<a class="list-group-item" href="{% url 'groups:single' pk=group.pk %}">
			     <h3 class="title list-group-item-heading">{{ group.name }}</h3>
					 <h4 class="title list-group-item-heading">Group ID: {{ group.groupid }}</h4>
					  <h4 class="title list-group-item-heading">Purpose: {{ group.purpose }}</h4>
						<br>
						 <h4 class="title list-group-item-heading">Created On: {{ group.group_date }}</h4>
						 <br>
			<div class="list-group-item-text container-fluid">
				{{ group.description_html|safe }}
				<br>
				<div class="row">
					<div class="col-md-4">
						<span class="badge">{{ group.member_set.count }}</span> member{{ group.member_set.count|pluralize }}
					</div>
				</div>
			</div>
		</a>
		{% endfor %}
	</div>
</div>
{% endblock %}

{% block postgroup %}
	<input type="button" class="btn btn-primary btn-large" value="Go back!" onclick="history.back()">
{% endblock %}