IntelliDataSmart/IntelliDataSmart/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from controlcenter.views import controlcenter
from django.urls import reverse

urlpatterns = [
    url(r"^$", views.HomePage.as_view(), name="home"),
    url(r"^landing/$", views.TestPage.as_view(), name="test"),
    url(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"),
    url(r"^gotoadmin/$", views.GotoAdmin, name="admin"),
    url(r"^admin/", admin.site.urls),
    url(r"^admin/dashboard/", controlcenter.urls),
    url(r"^accounts/", include("Accounts.urls", namespace="accounts")),
    url(r"^accounts/", include("django.contrib.auth.urls")),
    url(r"^members/", include("members.urls", namespace="members")),
    url(r"^groups/",include("groups.urls", namespace="groups")),
    url(r"^products/",include("products.urls", namespace="products")),
    url(r"^agreements/",include("agreements.urls", namespace="agreements")),
]

IntelliDataSmart/groups/urls.py
from django.conf.urls import url

from . import views

app_name = 'groups'

urlpatterns = [
    url(r"^$", views.ListGroups.as_view(), name="all"),
    url(r"^new/$", views.CreateGroup.as_view(), name="create"),
    url(r"^search/$", views.SearchGroupsForm, name="search"),
    url(r"^(?P<pk>\d+)/members/show/$", views.ShowMembersList.as_view(), name="show_members"),
    url(r"^(?P<pk>\d+)/agreements/show/$", views.ShowAgreementsList.as_view(), name="show_agreements"),
    url(r"^search/results/$", views.SearchGroupsList.as_view(), name="search_results"),
    url(r"^posts/in/(?P<pk>\d+)/$",views.SingleGroup.as_view(),name="single"),
    url(r"^version/(?P<pk>\d+)/$",views.VersionGroup, name="version"),
    url(r"^update/(?P<pk>\d+)/$",views.UpdateGroup.as_view(),name="update"),
    url(r"^delete/(?P<pk>\d+)/$",views.DeleteGroup.as_view(),name="delete"),
    url(r"^bulkupload/$",views.BulkUploadGroup,name="bulk"),
    url(r"join/(?P<slug>[-\w]+)/$",views.JoinGroup.as_view(),name="join"),
    url(r"leave/(?P<slug>[-\w]+)/$",views.LeaveGroup.as_view(),name="leave"),
    url(r"^rest/$",views.GroupList, name="rest"),
]

IntelliDataSmart/products/urls.py
from django.conf.urls import url

from . import views

app_name = 'products'

urlpatterns = [
    url(r"^$", views.ListProducts.as_view(), name="all"),
    url(r"^new/$", views.CreateProduct.as_view(), name="create"),
    url(r"^bulkupload/$",views.BulkUploadProduct,name="bulk"),
    url(r"^version/(?P<pk>\d+)/$",views.VersionProduct, name="version"),
    url(r"^search/$", views.SearchProductsForm, name="search"),
    url(r"^search/results/$", views.SearchProductsList.as_view(), name="search_results"),
    url(r"^posts/in/(?P<pk>\d+)/$",views.SingleProduct.as_view(),name="single"),
    url(r"^update/(?P<pk>\d+)/$",views.UpdateProduct.as_view(),name="update"),
    url(r"^delete/(?P<pk>\d+)/$",views.DeleteProduct.as_view(),name="delete"),
    url(r"^rest/$",views.ProductList, name="rest"),
]

IntelliDataSmart/products/models.py
from django.conf import settings
from datetime import datetime
from django.urls import reverse
from django.db import models
from django.utils.text import slugify

import misaka

from django.contrib.auth import get_user_model
User = get_user_model()

# https://docs.djangoproject.com/en/1.11/howto/custom-template-tags/#inclusion-tags
# This is for the in_group_members check template tag
from django import template
register = template.Library()

class Product(models.Model):
    productid = models.PositiveIntegerField()
    name = models.CharField(max_length=255)

    CHOOSE = 'Unknown Type'
    LIFE = 'LIFE'
    STD = 'STD'
    LTD = 'LTD'
    CI = 'CI'
    PRODUCT_CHOICES = (
        (CHOOSE, 'Unknown Type'),
        (LIFE, 'Life Insurance'),
        (STD, 'Short Term Disability'),
        (LTD, 'Long Term Disability'),
        (CI, 'Critical Illness'),
    )
    type = models.CharField(max_length=100,
                                      choices=PRODUCT_CHOICES,
                                      default=CHOOSE)

    slug = models.SlugField(allow_unicode=True)
    description = models.TextField(blank=True, default='')
    description_html = models.TextField(editable=False, default='', blank=True)
    #coverage = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    coverage_limit = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    price_per_1000_units = models.DecimalField(max_digits=4, decimal_places=2, default=0)
    creator = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    product_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return ("Name: "+self.name + "~" + "Type: "+self.type + "~" + "Coverage limit: "+ str(self.coverage_limit) + "~" + "Created on: "+self.product_date.strftime("%d-%b-%Y (%H:%M:%S.%f)"))

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("products:single", kwargs={"pk": self.pk})

    class Meta:
        ordering = ["-product_date"]
        unique_together = ("name", "type", "product_date")

IntelliDataSmart/products/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Product

PRODUCT_CHOICES = (
    ('LIFE', 'Life Insurance'),
    ('STD', 'Short Term Disability'),
    ('LTD', 'Long Term Disability'),
    ('CI', 'Critical Illness'),
    )

class ProductForm(forms.ModelForm):

    productid: forms.IntegerField()
    price_per_1000_units: forms.DecimalField()
    coverage_limit: forms.DecimalField()

    class Meta:
        model = Product

        fields = ('productid', 'name', 'type', 'description', 'price_per_1000_units', 'coverage_limit',)

        widgets = {

            'name': forms.TextInput(attrs={'class': 'textinputclass'}),

            'description': forms.Textarea(attrs={'class': 'editable medium-editor-textarea postcontent'}),



        }

IntelliDataSmart/products/views.py
from django.contrib import messages
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.http import HttpResponseForbidden
from django.core.exceptions import PermissionDenied
from django.contrib.auth.decorators import permission_required, login_required
from django.contrib.auth.decorators import user_passes_test
import time
from django.db.models import Q
from django.contrib.auth.mixins import(
    LoginRequiredMixin,
    PermissionRequiredMixin
)

from django.urls import reverse
from django.urls import reverse_lazy
from django.db import IntegrityError
from django.shortcuts import get_object_or_404
from django.views import generic
from django.db.models import Count
from groups.models import Group
from members.models import Member
from products.models import Product
from . import models
from . import forms
from products.forms import ProductForm
import csv
from groups.utils import BulkCreateManager
import os.path
from os import path
from django.utils.text import slugify
import misaka
import uuid

# For Rest rest_framework
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response
from products.serializers import ProductSerializer

class SingleProduct(LoginRequiredMixin, generic.DetailView):
    context_object_name = 'product_details'
    model = models.Product
    template_name = 'products/product_detail.html'

class ListProducts(LoginRequiredMixin, generic.ListView):
    model = models.Product
    template_name = 'products/product_list.html'

    def get_queryset(self):
        return models.Product.objects.all()


class CreateProduct(LoginRequiredMixin, PermissionRequiredMixin, generic.CreateView):
#    fields = ("name", "description")
    permission_required = 'products.add_product'
    context_object_name = 'product_details'
    redirect_field_name = 'products/product_list.html'
    form_class = forms.ProductForm
    model = models.Product
    template_name = 'products/product_form.html'

    def form_valid(self, form):
        if not self.request.user.has_perm('products.add_product'):
            raise HttpResponseForbidden()
        else:
            form.instance.creator = self.request.user

            return super().form_valid(form)


@permission_required("products.add_product")
@login_required
def VersionProduct(request, pk):
    # dictionary for initial data with
    # field names as keys
    context ={}

    # fetch the object related to passed id
    obj = get_object_or_404(Product, pk = pk)

    # pass the object as instance in form
    form = ProductForm(request.POST or None, instance = obj)

    # save the data from the form and
    # redirect to detail_view
    if form.is_valid():
            obj.pk = int(round(time.time() * 1000))
            form.instance.creator = request.user
            form.save()
            return HttpResponseRedirect(reverse("products:all"))

    else:

            # add form dictionary to context
            context["form"] = form

            return render(request, "products/product_form.html", context)


class UpdateProduct(LoginRequiredMixin, PermissionRequiredMixin, generic.UpdateView):
    permission_required = 'products.change_product'
    context_object_name = 'product_details'
    redirect_field_name = 'products/product_detail.html'
    form_class = forms.ProductForm
    model = models.Product
    template_name = 'products/product_form.html'

    def form_valid(self, form):

        if not self.request.user.has_perm('products.change_product'):
            raise HttpResponseForbidden()
        else:
            form.instance.creator = self.request.user
            return super().form_valid(form)



class DeleteProduct(LoginRequiredMixin, PermissionRequiredMixin, generic.DeleteView):
    permission_required = 'products.delete_product'
    context_object_name = 'product_details'
    form_class = forms.ProductForm
    model = models.Product
    template_name = 'products/product_delete_confirm.html'
    success_url = reverse_lazy("products:all")

    def form_valid(self, form):

        if not self.request.user.has_perm('products.delete_product'):
            raise HttpResponseForbidden()
        else:
            form.instance.creator = self.request.user
            return super().form_valid(form)


@login_required
def SearchProductsForm(request):
    return render(request,'products/product_search_form.html')


class SearchProductsList(LoginRequiredMixin, generic.ListView):
    login_url = '/login/'
    model = models.Product
    template_name = 'products/product_search_list.html'

    def get_queryset(self, **kwargs): # new
        query = self.request.GET.get('q', None)
        object_list = Product.objects.filter(
            Q(pk__icontains=query) | Q(name__icontains=query) | Q(type__icontains=query) | Q(description__icontains=query)
        )
        return object_list


@permission_required("products.add_product")
@login_required
def BulkUploadProduct(request):

    if not path.exists('/Users/suvojitdutta/Documents/PYTHON/PROJECTS/Docs/products.csv'):
        return render(request, "products/product_list.html", {'FileNotFound': True})
    else:
        with open('/Users/suvojitdutta/Documents/PYTHON/PROJECTS/Docs/products.csv', 'rt') as csv_file:
            bulk_mgr = BulkCreateManager(chunk_size=20)
            for row in csv.reader(csv_file):
                bulk_mgr.add(models.Product(productid=row[0],
                                          name=row[1],
                                          slug=slugify(row[1]),
                                          type=row[2],
                                          description=row[3],
                                          description_html = misaka.html(row[1]),
                                          coverage_limit=row[4],
                                          price_per_1000_units=row[5],
                                          creator = request.user
                                          ))
            bulk_mgr.done()

    return HttpResponseRedirect(reverse("products:all"))


@api_view(['GET', 'POST'])
def ProductList(request):

    if request.method == 'GET':
        contacts = Product.objects.all()
        serializer = ProductSerializer(contacts, many=True)
        return Response(serializer.data)
    elif request.method == 'POST':
        serializer = ProductSerializer(data=request.data)

    if serializer.is_valid():
        serializer.save()

        return Response(serializer.data, status=status.HTTP_201_CREATED)

        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

IntelliDataSmart/products/templates/products/product_base.html
{% extends "base.html" %}
{% block content %}

<div class="container">
  <div class="row">
    {% block preproduct %}{% endblock %}
    {% block product_content %}{% endblock %}
    {% block postproduct %}{% endblock %}
  </div>
</div>

{% endblock %}

IntelliDataSmart/products/templates/products/product_delete_confirm.html
{% extends "products/product_base.html" %}
{% load bootstrap3 %}

{% block product_content %}
  <form action="" method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input class='btn btn-danger' type="submit" value="Confirm" />
  </form>
{% endblock %}

IntelliDataSmart/products/templates/products/product_detail.html
{% extends "products/product_base.html" %}

{% block preproduct %}

<div class="dropdown">
  <button class="dropbtn btn btn-primary btn-large">Manage Products</button>
  <div class="dropdown-content">

  <a href="{% url 'products:version' pk=product_details.pk %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-pencil"></span> Version Product</a>
  &nbsp;
  <a href="{% url 'products:update' pk=product_details.pk %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-pencil"></span> Update Product</a>
  &nbsp;
  <a href="{% url 'products:delete' pk=product_details.pk %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-remove-circle"></span> Delete Product</a>

  </div>
</div>

&nbsp;
<input type="button" class="btn btn-primary btn-large" value="Go back!" onclick="history.back()">
&nbsp;

<h1>{{product_details.name}}</h1>
<h2>Type: {{product_details.type}}</h2>
<h2>Coverage Limit: {{product_details.coverage_limit}}</h2>
<h2>Price_per_1000_Units: {{product_details.price_per_1000_units}}</h2>
<h2>Created On: {{product_details.product_date}}</h2>
<h2>Created By: {{product_details.creator}}</h2>
<div style="background-color: rgba(255, 255, 255, 0.8);" data-spy="scroll" data-target=".navbar">
  <div class="list-group-item-text container-fluid">
    <h4 style="color:black;">{{ product_details.description_html|safe }}</h4>
  </div>
</div>


{% endblock %}

IntelliDataSmart/products/templates/products/product_form.html
{% extends "products/product_base.html" %}
{% load bootstrap3 %}

{% block product_content %}
<h4>Edit Product</h4>
  <!-- <form method="POST" action="{% url 'groups:create' %}" id="groupForm"> -->
  <form method="POST">
  	{% csrf_token %}
  	{% bootstrap_form form %}
  	<input type="submit" value="Save" class="btn btn-primary btn-large">
    &nbsp;
    <a href="{% url 'products:all'%}" class="btn btn-primary btn-large">Cancel</a>
  </form>
{% endblock %}

IntelliDataSmart/products/templates/products/product_list.html
{% extends "products/product_base.html" %}

{% block preproduct %}
<div class="col-md-4">
	<div class="content">
		{% if user.is_authenticated %}
		<h2>
			Welcome
			{{user.username }}

		</h2>

    {% endif %}
		<h2>Products</h2>

		{% if not object_list %}
  			<p>No products available at this time! Go ahead and create a product if needed!</p>
		{% else %}
				<p>Welcome to the Products Page! Select a product that you want to work with!</p>
		{% endif %}

	</div>

	{% if user.is_authenticated %}
	<a href="{% url 'products:create' %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-plus-sign"></span> Create New Product!</a>
	&nbsp;
	<a href="{% url 'products:bulk' %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-plus-sign"></span> Uplaod Products!</a>
	&nbsp;
	{% if FileNotFound %}
    <div id="some_flag" title="Some Flag">
        <h2>File Does Not Exist!</h2>
    </div>
	{% endif %}

	{% endif %}
</div>
{% endblock %}

{% block product_content %}
<div class="col-md-8">
	<div class="list-group">
		{% for product in object_list %}
			<a class="list-group-item" href="{% url 'products:single' pk=product.pk %}">
			     <h3 class="title list-group-item-heading">{{ product.name }}</h3>
					 <h4 class="title list-group-item-heading">Type: {{ product.type }}</h4>
					  <h4 class="title list-group-item-heading">Coverage Limit: {{ product.coverage_limit }}</h4>
						 <h4 class="title list-group-item-heading">Price_per_1000_Units: {{ product.price_per_1000_units }}</h4>
					 <h4 class="title list-group-item-heading">Created On: {{ product.product_date }}</h4>
					 <h4 class="title list-group-item-heading">Created By: {{ product.creator }}</h4>
					 <br>
			<div class="list-group-item-text container-fluid">
				{{ product.description_html|safe }}
			</div>
		</a>
		{% endfor %}
	</div>
</div>
{% endblock %}

IntelliDataSmart/products/templates/products/product_search_form.html
{% extends "products/product_base.html" %}

{% block preproduct %}
<h4>Search Product</h4>
  <!-- <form method="POST" action="{% url 'groups:create' %}" id="groupForm"> -->
  <form action="{% url 'products:search_results' %}" method="GET">
  	{% csrf_token %}
    <input name="q" type="text" placeholder="Search...">
    &nbsp;
    <button class="btn btn-primary btn-large" type="submit" >Search</button>
  </form>

{% endblock %}

IntelliDataSmart/products/templates/products/product_search_list.html
{% extends "products/product_base.html" %}
{% load bootstrap3 %}

{% block product_content %}
<div class="col-md-8">
	<div class="list-group">
		{% for product in object_list %}
			<a class="list-group-item" href="{% url 'products:single' pk=product.pk %}">
			     <h3 class="title list-group-item-heading">{{ product.name }}</h3>
					 <h4 class="title list-group-item-heading">Type: {{ product.type }}</h4>
					 <h4 class="title list-group-item-heading">Created On: {{ product.product_date }}</h4>
					 <h4 class="title list-group-item-heading">Created By: {{ product.creator }}</h4>
					 <br>
			<div class="list-group-item-text container-fluid">
				{{ product.description_html|safe }}
			</div>
		</a>
		{% endfor %}
	</div>
</div>
{% endblock %}

{% block postproduct %}
	<input type="button" class="btn btn-primary btn-large" value="Go back!" onclick="history.back()">
{% endblock %}