IntelliDataSmart/Accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views
from django.urls import reverse

app_name = 'Accounts'

urlpatterns = [
    url(r"login/$", auth_views.LoginView.as_view(template_name="Accounts/login.html"),name='login'),
    url(r"logout/$", auth_views.LogoutView.as_view(), name="logout"),
    url(r"signup/$", views.SignUp.as_view(), name="signup"),
    url(r"editprofile/(?P<pk>\d+)/$", views.EditProfile.as_view(), name="editprofile"),
]

IntelliDataSmart/IntelliDataSmart/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from controlcenter.views import controlcenter
from django.urls import reverse

urlpatterns = [
    url(r"^$", views.HomePage.as_view(), name="home"),
    url(r"^landing/$", views.TestPage.as_view(), name="test"),
    url(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"),
    url(r"^gotoadmin/$", views.GotoAdmin, name="admin"),
    url(r"^admin/", admin.site.urls),
    url(r"^admin/dashboard/", controlcenter.urls),
    url(r"^accounts/", include("Accounts.urls", namespace="accounts")),
    url(r"^accounts/", include("django.contrib.auth.urls")),
    url(r"^members/", include("members.urls", namespace="members")),
    url(r"^groups/",include("groups.urls", namespace="groups")),
    url(r"^products/",include("products.urls", namespace="products")),
    url(r"^agreements/",include("agreements.urls", namespace="agreements")),
]

IntelliDataSmart/groups/urls.py
from django.conf.urls import url

from . import views

app_name = 'groups'

urlpatterns = [
    url(r"^$", views.ListGroups.as_view(), name="all"),
    url(r"^new/$", views.CreateGroup.as_view(), name="create"),
    url(r"^search/$", views.SearchGroupsForm, name="search"),
    url(r"^(?P<pk>\d+)/members/show/$", views.ShowMembersList.as_view(), name="show_members"),
    url(r"^(?P<pk>\d+)/agreements/show/$", views.ShowAgreementsList.as_view(), name="show_agreements"),
    url(r"^search/results/$", views.SearchGroupsList.as_view(), name="search_results"),
    url(r"^posts/in/(?P<pk>\d+)/$",views.SingleGroup.as_view(),name="single"),
    url(r"^version/(?P<pk>\d+)/$",views.VersionGroup, name="version"),
    url(r"^update/(?P<pk>\d+)/$",views.UpdateGroup.as_view(),name="update"),
    url(r"^delete/(?P<pk>\d+)/$",views.DeleteGroup.as_view(),name="delete"),
    url(r"^bulkupload/$",views.BulkUploadGroup,name="bulk"),
    url(r"join/(?P<slug>[-\w]+)/$",views.JoinGroup.as_view(),name="join"),
    url(r"leave/(?P<slug>[-\w]+)/$",views.LeaveGroup.as_view(),name="leave"),
    url(r"^rest/$",views.GroupList, name="rest"),
]

IntelliDataSmart/members/urls.py
from django.conf.urls import url

from . import views

app_name = 'members'

urlpatterns = [
    url(r"^$",views.ListMembers.as_view(),name='all'),
    url(r"^(?P<pk>\d+)/$",views.SingleMember.as_view(),name='single'),
    url(r"^version/(?P<pk>\d+)/$",views.VersionMember, name="version"),
    url(r"^search/$", views.SearchMembersForm, name="search"),
    url(r"^search/results/$", views.SearchMembersList.as_view(), name="search_results"),
    url(r"^(?P<pk>\d+)/create/$",views.CreateMember.as_view(),name='create'),
    url(r"^(?P<pk>\d+)/upload/$",views.BulkUploadMember, name='upload'),
    url(r"^update/(?P<pk>\d+)/$",views.UpdateMember.as_view(),name='update'),
    url(r"^delete/(?P<pk>\d+)/$",views.DeleteMember.as_view(),name='delete'),
    url(r"^rest/$",views.MemberList, name="rest"),
]

IntelliDataSmart/members/models.py
from django.conf import settings
from datetime import datetime
import uuid
from django.urls import reverse
from django.db import models
from django.utils.text import slugify
from groups.models import Group
from phonenumber_field.modelfields import PhoneNumberField
# from accounts.models import User

import misaka

from django.contrib.auth import get_user_model
User = get_user_model()

# https://docs.djangoproject.com/en/1.11/howto/custom-template-tags/#inclusion-tags
# This is for the in_group_members check template tag
from django import template
register = template.Library()

class Member(models.Model):
    memberid = models.CharField(max_length=255, null=True, blank=True)
    name = models.CharField(max_length=256)
    slug = models.SlugField(allow_unicode=True)
    age = models.PositiveIntegerField()
    email = models.EmailField(max_length=254, blank=True, null=True)
    phone = PhoneNumberField(null=True, blank=True, unique=False)

    group = models.ForeignKey(Group, on_delete=models.SET_NULL, null=True, blank=True, related_name="member_set")

    creator = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    member_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):

        if (self.memberid == None):
            var = str(uuid.uuid4())
            self.memberid = var[26:36]

        self.slug = slugify(self.name)
    #    self.description_html = misaka.html(self.description)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("members:single", kwargs={"pk": self.pk})


    class Meta:
        ordering = ["-member_date"]
        #unique_together = ["name", "group"]

IntelliDataSmart/members/forms.py
from django import forms
from django.core.exceptions import ValidationError
from members.models import *

from .models import Member
from phonenumber_field.formfields import PhoneNumberField


class MemberForm(forms.ModelForm):
    age: forms.IntegerField()
    phone = PhoneNumberField()
    # this function will be used for the validation
    def clean(self):

                # data from the form is fetched using super function
                super(MemberForm, self).clean()

                # extract the username and text field from the data
                phone = self.cleaned_data.get('phone')
                age = self.cleaned_data.get('age')

                # age range check
                if (age <= 0 or age >= 100):
                    self._errors['age'] = self.error_class([
                        'Age is valid only in range of 1 and 99'])

                # return any errors if found
                return self.cleaned_data


    class Meta:
        model = Member
        exclude = ('slug','creator')
        #fields = ('name', 'age')
        #fields = '__all__'
        widgets = {
            'memberid': forms.TextInput(attrs={'readonly':'readonly'}),
            'name': forms.TextInput(attrs={'class': 'textinputclass'}),
            'email_address': forms.EmailField(max_length = 200),
            'creator': forms.TextInput(attrs={'readonly':'readonly'}),

        }

IntelliDataSmart/members/views.py
from django.contrib import messages
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.http import HttpResponseForbidden
from django.core.exceptions import PermissionDenied
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test
import time
from django.db.models import Q
from django.contrib.auth.mixins import(
    LoginRequiredMixin,
    PermissionRequiredMixin
)

from django.urls import reverse
from django.urls import reverse_lazy
from django.db import IntegrityError
from django.shortcuts import get_object_or_404
from django.views import generic
from groups.models import Group
from members.models import Member
from . import models
from . import forms
from members.forms import MemberForm
import csv
from groups.utils import BulkCreateManager
import os.path
from os import path
from django.utils.text import slugify
import misaka
import uuid

# For Rest rest_framework
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response
from members.serializers import MemberSerializer


class SingleMember(LoginRequiredMixin, generic.DetailView):
    context_object_name = 'member_details'
    model = models.Member
    template_name = 'members/member_detail.html'
    #form_class = forms.MemberForm

class ListMembers(LoginRequiredMixin, generic.ListView):
    context_object_name = 'member_list'
    model = models.Member
    template_name = 'members/member_list.html'

    #form_class = forms.MemberForm

    def get_queryset(self):
    #    return Member.objects.filter(group=group_name)
    #    return Member.objects.all
        return models.Member.objects.prefetch_related('group')


class CreateMember(LoginRequiredMixin, PermissionRequiredMixin, generic.CreateView):
    #fields = ("name", "age")
    permission_required = 'members.add_member'
    template_name = 'members/member_form.html'
    context_object_name = 'member_details'
    redirect_field_name = 'members/member_detail.html'
    model = models.Member
    form_class = forms.MemberForm

    def dispatch(self, request, *args, **kwargs):
        """
        Overridden so we can make sure the `Group` instance exists
        before going any further.
        """
        self.group = get_object_or_404(models.Group, pk=kwargs['pk'])
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):

        if not self.request.user.has_perm('members.add_member'):
            raise HttpResponseForbidden()
        else:
            """
            Overridden to add the group relation to the `Member` instance.
            """
            form.instance.group = self.group
            form.instance.creator = self.request.user
            return super().form_valid(form)


@login_required
@permission_required("members.add_member")
def VersionMember(request, pk):
    # dictionary for initial data with
    # field names as keys
    context ={}

    # fetch the object related to passed id
    obj = get_object_or_404(Member, pk = pk)

    # pass the object as instance in form
    form = MemberForm(request.POST or None, instance = obj)

    # save the data from the form and
    # redirect to detail_view
    if form.is_valid():
            obj.pk = int(round(time.time() * 1000))
            form.instance.creator = request.user
            form.save()
            return HttpResponseRedirect(reverse("members:all"))

    else:

            # add form dictionary to context
            context["form"] = form

            return render(request, "members/member_form.html", context)


class UpdateMember(LoginRequiredMixin, PermissionRequiredMixin, generic.UpdateView):
    #fields = ("name", "age")
    permission_required = 'members.change_member'
    template_name = 'members/member_form.html'
    #context_object_name = 'member_details'
    redirect_field_name = 'members/member_detail.html'
    model = models.Member
    form_class = forms.MemberForm

    def form_valid(self, form):

        if not self.request.user.has_perm('members.change_member'):
            raise HttpResponseForbidden()
        else:
            form.instance.creator = self.request.user
            return super().form_valid(form)


class DeleteMember(LoginRequiredMixin, PermissionRequiredMixin, generic.DeleteView,):
    permission_required = 'members.delete_member'
    context_object_name = 'member_details'
    form_class = forms.MemberForm
    model = models.Member
    template_name = 'members/member_delete_confirm.html'
    success_url = reverse_lazy("members:all")


    def delete(self, *args, **kwargs):
        messages.success(self.request, "Member Deleted")
        return super().delete(*args, **kwargs)

    def form_valid(self, form):

        if not self.request.user.has_perm('members.delete_member'):
            raise HttpResponseForbidden()
        else:
            return super().form_valid(form)


def SearchMembersForm(request):
    return render(request,'members/member_search_form.html')


class SearchMembersList(LoginRequiredMixin, generic.ListView):
    login_url = '/login/'
    model = models.Member
    template_name = 'members/member_search_list.html'

    def get_queryset(self, **kwargs): # new
        query = self.request.GET.get('q', None)
        object_list = models.Member.objects.filter(
            Q(name__icontains=query) | Q(age__icontains=query)
        )
        return object_list


@permission_required("members.add_member")
@login_required
def BulkUploadMember(request, pk, *args, **kwargs):

    if not path.exists('/Users/suvojitdutta/Documents/PYTHON/PROJECTS/Docs/members.csv'):
        return render(request, "members/member_list.html", {'FileNotFound': True})
    else:
        with open('/Users/suvojitdutta/Documents/PYTHON/PROJECTS/Docs/members.csv', 'rt') as csv_file:
            bulk_mgr = BulkCreateManager(chunk_size=20)
            for row in csv.reader(csv_file):
                bulk_mgr.add(models.Member(memberid = str(uuid.uuid4())[26:36],
                                          name=row[0],
                                          slug=slugify(row[0]),
                                          age=int(row[1]),
                                          email=row[2],
                                          phone=row[3],
                                          group=get_object_or_404(models.Group, pk=pk),
                                          creator = request.user
                                          ))
            bulk_mgr.done()

    return HttpResponseRedirect(reverse("members:all"))


@api_view(['GET', 'POST'])
def MemberList(request):

    if request.method == 'GET':
        contacts = Member.objects.all()
        serializer = MemberSerializer(contacts, many=True)
        return Response(serializer.data)
    elif request.method == 'POST':
        serializer = MemberSerializer(data=request.data)

    if serializer.is_valid():
        serializer.save()

        return Response(serializer.data, status=status.HTTP_201_CREATED)

        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

IntelliDataSmart/members/templates/members/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Intelli Data</title>
    <!-- Latest compiled and minified CSS -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'simplesocial/css/master.css'%}">


  </head>


  <body>

    <nav class="navbar  mynav" role="navigation" id="navbar">
    			<div class="container">

            <a class="navbar-brand mynav" href="{% url 'home' %}">Home</a>

    					<ul class="nav navbar-nav navbar-right">
    						{% if user.is_authenticated %}
                      <li><a class="navbar-brand mynav" href="{% url 'groups:all' %}" class="btn btn-simple">Groups</a></li>
                      <li><a class="navbar-brand mynav" href="{% url 'members:all' %}" class="btn btn-simple">Members</a></li>
                      <li><a class="navbar-brand mynav" href="{% url 'Accounts:logout' %}">Log out</a></li>
    						{% else %}
    						  <!--    <li><a href="{% url 'accounts:login' %}" class="btn btn-simple">Log in</a></li>
    						      <li><a href="{% url 'accounts:signup' %}" class="btn btn-simple">Sign up</a></li> -->
                      <li><a class="navbar-brand mynav" href="{% url 'Accounts:login' %}">Log in</a></li>
    						      <li><a class="navbar-brand mynav" href="{% url 'Accounts:signup' %}">Sign up</a></li>
    						{% endif %}
    					</ul>



    			</div>
    		</nav>
        <div class="container mycontent">
          {% block content %}

          {% endblock %}

        </div>

      <style>
          body {
            background-image: url('{% static "images/darknewyorkcity.jpg" %}');
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: cover;
            overflow: scroll;
          }
      </style>

<canvas id="canvas"></canvas>

  </body>
<!--  <script src="{% static "simplesocial/js/master.js"%}" type="text/javascript" ></script>  -->

</html>

IntelliDataSmart/members/templates/members/member_base.html
{% extends "base.html" %}


{% block content %}


<div class="container">
  <div class="row">
    {% block premember %}{% endblock %}
    {% block member_content %}{% endblock %}
    {% block postmember %}{% endblock %}
  </div>
</div>

{% endblock %}

IntelliDataSmart/members/templates/members/member_delete_confirm.html
{% extends "members/member_base.html" %}
{% load bootstrap3 %}

{% block member_content %}
  <form action="" method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input class='btn btn-danger' type="submit" value="Confirm" />
  </form>
{% endblock %}

IntelliDataSmart/members/templates/members/member_detail.html
{% extends "members/member_base.html" %}

{% block premember %}

<div class="dropdown">
  <button class="dropbtn btn btn-primary btn-large">Manage Members</button>
  <div class="dropdown-content">

  <a href="{% url 'members:version' pk=member_details.pk %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-pencil"></span> Version Member</a>
  &nbsp;
  <a href="{% url 'members:update' pk=member_details.pk %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-pencil"></span> Update Member</a>
  &nbsp;
  <a href="{% url 'members:delete' pk=member_details.pk %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-remove-circle"></span> Delete Member</a>


  </div>
</div>

&nbsp;
<input type="button" class="btn btn-primary btn-large" value="Go back!" onclick="history.back()">
&nbsp;

<h1>{{member_details.name}}</h1>
<h2>Member ID: {{member_details.memberid}}</h2>
<h2>Age: {{member_details.age}}</h2>
<h2>Email: {{member_details.email}}</h2>
<h2>Phone: {{member_details.phone}}</h2>
<h2>Group: {{member_details.group}}</h2>
<h2>Created On: {{member_details.member_date}}</h2>
<h2>Created By: {{member_details.creator}}</h2>

{% endblock %}

IntelliDataSmart/members/templates/members/member_form.html
{% extends "members/member_base.html" %}
{% load bootstrap3 %}

{% block member_content %}

<h4>Edit Member</h4>
  <form method="POST">
  	{% csrf_token %}
  	{% bootstrap_form form %}
  	<input type="submit" value="Save" class="btn btn-primary btn-large">
    &nbsp;
    <a href="{% url 'members:all'%}" class="btn btn-primary btn-large">Cancel</a>
  </form>

{% endblock %}

IntelliDataSmart/members/templates/members/member_list copy.html
{% extends "members/member_base.html" %}

{% block premember %}
<div class="col-md-4">
	<div class="content">
		{% if user.is_authenticated %}
		<h2>
			Welcome back
			{{user.username }}
		</h2>

    {% endif %}
			<h2>Members</h2>

			<p>Welcome to the Members Page! Select a Member that you want to work on!</p>
	</div>
	{% if user.is_authenticated %}
	<a href="{% url 'members:create' pk=group.pk %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-plus-sign"></span> Create New Member!</a>
	{% endif %}
</div>
{% endblock %}

{% block member_content %}
<div class="col-md-8">
	<div class="list-group">
		{% for member in object_list %}
		  <a class="list-group-item" href="{% url 'member:single' pk=member.pk %}">
			     <h3 class="title list-group-item-heading">{{ member.name }}</h3>
					 <h3 class="title list-group-item-heading">Age: {{ member.age }}</h3>
					 <h3 class="title list-group-item-heading">Group: {{ member.group }}</h3>
		</a>
		{% endfor %}
	</div>
</div>
{% endblock %}

IntelliDataSmart/members/templates/members/member_list.html
{% extends "members/member_base.html" %}

{% block premember %}
<div class="col-md-4">
	<div class="content">
		{% if user.is_authenticated %}
		<h2>
			Welcome
			{{user.username }}
		</h2>

    {% endif %}
		<h2>Members</h2>

		{% if not object_list %}
  			<p>No members available at this time! Go back and add a member to this group!</p>
		{% else %}
				<p>Welcome to the Members Page! Select a member that you want to work on!</p>
		{% endif %}

		<br>
		<input type="button" class="btn btn-primary btn-large" value="Go back!" onclick="history.back()">

	</div>
</div>
{% endblock %}

{% block member_content %}
<div class="col-md-8">
	<div class="list-group">
		{% for member in object_list %}
		  <a class="list-group-item" href="{% url 'members:single' pk=member.pk %}">
			     <h3 class="title list-group-item-heading">{{ member.name }}</h3>
					 <h4 class="title list-group-item-heading">Member ID: {{ member.memberid }}</h4>
					 <h4 class="title list-group-item-heading">Age: {{ member.age }}</h4>
					 <h4 class="title list-group-item-heading">Email: {{ member.email }}</h4>
					 <h4 class="title list-group-item-heading">Phone: {{ member.phone }}</h4>
					 <h4 class="title list-group-item-heading">Group: {{ member.group }}</h4>
					 <h4 class="title list-group-item-heading">Created On: {{ member.member_date }}</h4>
					 <h4 class="title list-group-item-heading">Created By: {{ member.creator }}</h4>
		</a>
		{% endfor %}
	</div>
</div>
{% endblock %}

IntelliDataSmart/members/templates/members/member_search_form.html
{% extends "members/member_base.html" %}

{% block premember %}
<h4>Search Member</h4>
  <form action="{% url 'members:search_results' %}" method="GET">
  	{% csrf_token %}
    <input name="q" type="text" placeholder="Search...">
    &nbsp;
    <button class="btn btn-primary btn-large" type="submit" >Search</button>
  </form>

{% endblock %}

IntelliDataSmart/members/templates/members/member_search_list.html
{% extends "members/member_base.html" %}
{% load bootstrap3 %}

{% block member_content %}
<div class="col-md-8">
	<div class="list-group">
		{% for member in object_list %}
		  <a class="list-group-item" href="{% url 'members:single' pk=member.pk %}">
			     <h3 class="title list-group-item-heading">{{ member.name }}</h3>
					  <h4 class="title list-group-item-heading">Member ID: {{ member.memberid }}</h4>
					 <h4 class="title list-group-item-heading">Age: {{ member.age }}</h4>
					 <h4 class="title list-group-item-heading">Email: {{ member.email }}</h4>
					 <h4 class="title list-group-item-heading">Group: {{ member.group }}</h4>
					 <h4 class="title list-group-item-heading">Created On: {{ member.member_date }}</h4>
					 <h4 class="title list-group-item-heading">Created By: {{ member.creator }}</h4>
		</a>
		{% endfor %}
	</div>
</div>
{% endblock %}

{% block postmember %}
	<input type="button" class="btn btn-primary btn-large" value="Go back!" onclick="history.back()">
{% endblock %}